apiVersion: v1
kind: Service
metadata:
  name: podinfo-app
  labels:
    app: podinfo
spec:
  selector:
    app: podinfo
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898j
